### PR TITLE
About page: fix little things, clearer text

### PR DESCRIPTION
**Pull request by achadwick**
A little update to the work done in #7.

I've fixed a few punctuation and grammar errors, and tried to make the text read clearer using http://www.hemingwayapp.com/.

Added a few buzzwords, and explain the sort of flow I try to let happen.

One clause (ish) per line. That's nicer for future diffs.

### CODE REVIEW

**Comment by odysseywestra** [comment]
Looks good so far, but you have two paragraphs repeating itself in two different ways.

> The standard brushes let you simulate traditional media such as charcoal and ink. But feel free to experiment! It's easy to make expressive, artistic new brushes that don't respond like anything realistic.
> 
> The standard brushes can emulate traditional media like charcoal, pencils, ink, or paint. But you don't have to limit yourself to just the standard ones. It’s easy to make expressive, artful new brushes that don’t respond like anything conventional.

Also you probably could remove the clause from this sentence. It not only make it easier to read, but won't clash with next sentence. 

> You can reveal the tools you need when you need them, but while you're in the flow MyPaint keeps it distraction-free. Focus on the art you make, not the tool you make it with.

Here's my suggestion:

> You can reveal the tools you need when you need them. It allows you to focus on the art you make, not the tools you make art with.

The http://humingwayapp.com looks like a pretty interesting web app. I will definitively take a look into it.

Once you fix those, I'll merge your PR into the website. Awesome Sauce and Thanks!

**Comment by achadwick** [comment]
Oops, didn't spot the duplicated revision.

Fixed. I kept "distraction-free" in the other para for buzzword compliance, but I think I've explained why better now.

**Comment by odysseywestra** [comment]
You did it again... I think that web app may be causing it. ^^'

> Fullscreen mode declutters the interface, leaving you with just your brush and your creativity. You can still reveal the tools you need when you need them. This distraction-free approach means you can focus better on the art you make, not the tool you make it with.
> 
> Fullscreen mode declutters the interface, leaving you with just your brush and your creativity. You can reveal the tools you need when you need them. Having a distraction-free screen means you can focus on the art you make, not the tool you make it with.

**Comment by achadwick** [comment]
Ah no, that's my fault for not adding before pushing. Sorry! ☺ Fixed now.

**Comment by odysseywestra** [comment]
Okay It looks good now, I'll accept the PR and deploy it.

**Pull request merged**
